# Generated by Django 4.0.4 on 2023-04-17 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nambre del usuario', max_length=50, verbose_name='Name')),
                ('cookies', models.JSONField(help_text='Cookies de sesión del usuario', verbose_name='Cookies')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el usuario está activo', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
