# Generated by Django 4.0.4 on 2023-04-17 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la ubicación', max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
            },
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(help_text='Host del proxy', max_length=50, verbose_name='Host')),
                ('port', models.IntegerField(help_text='Puerto del proxy', verbose_name='Puerto')),
                ('user', models.CharField(help_text='Usuario del proxy', max_length=50, verbose_name='Usuario')),
                ('password', models.CharField(help_text='Contraseña del proxy', max_length=50, verbose_name='Contraseña')),
                ('location', models.ForeignKey(blank=True, help_text='Ubicación del proxy', null=True, on_delete=django.db.models.deletion.CASCADE, to='botviews.locations', verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Proxy',
                'verbose_name_plural': 'Proxies',
            },
        ),
    ]
