# Generated by Django 4.0.4 on 2023-04-17 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botviews', '0002_locations_proxy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Locations',
            new_name='Location',
        ),
    ]
