# Generated by Django 4.0.4 on 2023-04-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botviews', '0004_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(help_text='Nombre de la ubicación', max_length=50, unique=True, verbose_name='Nombre'),
        ),
    ]
