# Generated by Django 4.0.4 on 2023-04-17 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botviews', '0005_alter_location_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Ajuste', 'verbose_name_plural': 'Ajustes'},
        ),
    ]
