# Generated by Django 4.0.4 on 2023-04-17 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botviews', '0006_alter_settings_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='Setting',
        ),
    ]
