# Generated by Django 4.0.4 on 2023-04-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botviews', '0009_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='value',
            field=models.CharField(help_text='Token de validación', max_length=50, unique=True, verbose_name='Valor'),
        ),
    ]
