# Generated by Django 4.0.4 on 2023-05-10 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0082_alter_comment_datetime'),
        ('botviews', '0012_alter_token_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.IntegerField(help_text='Minuto de la donación', verbose_name='Minuto')),
                ('amount', models.FloatField(help_text='Cantidad de la donación', verbose_name='Cantidad')),
                ('message', models.CharField(help_text='Mensaje de la donación', max_length=100, verbose_name='Mensaje')),
                ('status', models.BooleanField(default=False, help_text='Indica si la donación ha sido procesada', verbose_name='Estado')),
                ('stream', models.ForeignKey(help_text='Stream de la donación', on_delete=django.db.models.deletion.CASCADE, to='app.stream', verbose_name='Stream')),
                ('user', models.ForeignKey(help_text='Usuario que ha realizado la donación', on_delete=django.db.models.deletion.CASCADE, to='botviews.user', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Donación',
                'verbose_name_plural': 'Donaciones',
            },
        ),
    ]
