# Generated by Django 4.0.4 on 2023-05-11 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botviews', '0013_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.IntegerField(help_text='Cantidad de la donación', verbose_name='Cantidad'),
        ),
    ]
