# Generated by Django 4.0.4 on 2023-05-11 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botviews', '0014_alter_donation_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(help_text='Nambre del usuario', max_length=50, unique=True, verbose_name='Name'),
        ),
    ]
