# Generated by Django 4.0.4 on 2023-05-14 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botviews', '0015_alter_user_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
