# Generated by Django 4.0.4 on 2023-05-15 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botviews', '0016_delete_donation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Bot',
        ),
    ]
