# Generated by Django 4.0.4 on 2023-05-15 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botviews', '0017_rename_user_bot'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bot',
            new_name='User',
        ),
    ]
