# Generated by Django 4.0.4 on 2023-05-15 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botviews', '0018_rename_bot_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Bot', 'verbose_name_plural': 'Bots'},
        ),
    ]
