# Generated by Django 4.0.4 on 2023-05-26 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botviews', '0019_alter_user_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proxy',
            name='location',
        ),
        migrations.RemoveField(
            model_name='proxy',
            name='password',
        ),
        migrations.RemoveField(
            model_name='proxy',
            name='user',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
