# Generated by Django 4.0.4 on 2023-05-27 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botviews', '0020_remove_proxy_location_remove_proxy_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='password',
            field=models.CharField(default='', help_text='Contraseña del proxy', max_length=50, verbose_name='Contraseña'),
        ),
        migrations.AddField(
            model_name='proxy',
            name='user',
            field=models.CharField(default='', help_text='Usuario del proxy', max_length=50, verbose_name='Usuario'),
        ),
    ]
