# Generated by Django 4.0.4 on 2023-06-19 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botviews', '0022_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
