# Generated by Django 4.0.4 on 2023-06-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botviews', '0023_remove_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='ComunidadMC', help_text='Contraseña del usuario', max_length=50, verbose_name='Password'),
        ),
    ]
