# Generated by Django 4.0.4 on 2022-12-19 05:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_access_token_user_picture_user_refresh_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='refresh_token',
        ),
        migrations.AddField(
            model_name='user',
            name='access token',
            field=models.CharField(default=0, help_text='user access token', max_length=50, verbose_name='access token'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last login',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 23, 38, 53, 566335), help_text='user last login', verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='user',
            name='refresh token',
            field=models.CharField(default=0, help_text='user refresh token', max_length=50, verbose_name='refresh token'),
            preserve_default=False,
        ),
    ]
