# Generated by Django 4.0.4 on 2022-12-19 05:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_user_access_token_remove_user_refresh_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last login',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 23, 39, 23, 787542), help_text='user last login', verbose_name='last login'),
        ),
    ]
