# Generated by Django 4.0.4 on 2022-12-22 23:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_user_last login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='picture',
        ),
        migrations.AddField(
            model_name='user',
            name='apellido',
            field=models.CharField(blank=True, help_text='apellido', max_length=100, null=True, verbose_name='apellido'),
        ),
        migrations.AddField(
            model_name='user',
            name='foto',
            field=models.URLField(blank=True, help_text='foto de perfil de twitch', verbose_name='foto'),
        ),
        migrations.AddField(
            model_name='user',
            name='nombre',
            field=models.CharField(blank=True, help_text='nombre', max_length=100, null=True, verbose_name='nombre'),
        ),
        migrations.AddField(
            model_name='user',
            name='país',
            field=models.CharField(blank=True, help_text='país', max_length=100, null=True, verbose_name='país'),
        ),
        migrations.AddField(
            model_name='user',
            name='teléfono',
            field=models.CharField(blank=True, help_text='teléfono', max_length=20, null=True, verbose_name='teléfono'),
        ),
        migrations.AddField(
            model_name='user',
            name='usuario',
            field=models.CharField(blank=True, help_text='nombre de usuario de twitch', max_length=100, verbose_name='usuario'),
        ),
        migrations.AddField(
            model_name='user',
            name='zona horaria',
            field=models.CharField(blank=True, help_text='zona horaria', max_length=100, null=True, verbose_name='zona horaria'),
        ),
        migrations.AddField(
            model_name='user',
            name='último login',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='fecha de último inicio de sesión', verbose_name='últimos login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='access token',
            field=models.CharField(help_text='user token de twitch', max_length=50, verbose_name='access token'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='email de twitch', max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(editable=False, help_text='id de twitch', primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='refresh token',
            field=models.CharField(help_text='refresh token de twitch', max_length=50, verbose_name='refresh token'),
        ),
    ]
