# Generated by Django 4.0.4 on 2022-12-23 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_user_last login_remove_user_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='access token',
            new_name='access_token',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='país',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='nombre',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='último login',
            new_name='last_login',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='apellido',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='teléfono',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='foto',
            new_name='picture',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='refresh token',
            new_name='refresh_token',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='zona horaria',
            new_name='time_zone',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='usuario',
            new_name='user_name',
        ),
    ]
