# Generated by Django 4.0.4 on 2022-12-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_access token_user_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, help_text='indica si el usuario está activo', verbose_name='activo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='access_token',
            field=models.CharField(help_text='access token generado por twitch', max_length=50, verbose_name='access token'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, help_text='país de residencia', max_length=100, null=True, verbose_name='país'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, help_text='nombre real del usuario', max_length=100, null=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, help_text='apellido real del usuario', max_length=100, null=True, verbose_name='apellido'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='teléfono con código de país', max_length=20, null=True, verbose_name='teléfono'),
        ),
        migrations.AlterField(
            model_name='user',
            name='refresh_token',
            field=models.CharField(help_text='refresh token generado por twitch', max_length=50, verbose_name='refresh token'),
        ),
        migrations.AlterField(
            model_name='user',
            name='time_zone',
            field=models.CharField(blank=True, help_text='zona horaria de residencia', max_length=100, null=True, verbose_name='zona horaria'),
        ),
    ]
