# Generated by Django 4.0.4 on 2023-01-04 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_user_is_active_alter_user_access_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.IntegerField(editable=False, help_text='id del país', primary_key=True, serialize=False, verbose_name='id')),
                ('country', models.CharField(help_text='país de residencia', max_length=100, verbose_name='país')),
            ],
        ),
        migrations.CreateModel(
            name='TimeZone',
            fields=[
                ('id', models.IntegerField(editable=False, help_text='id de la zona horaria', primary_key=True, serialize=False, verbose_name='id')),
                ('time_zone', models.CharField(help_text='zona horaria', max_length=100, verbose_name='zona horaria')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, help_text='indica si el usuario ha validado su cuenta con whatsapp', verbose_name='activo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.ForeignKey(blank=True, help_text='país de residencia', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.country', verbose_name='país'),
        ),
        migrations.AlterField(
            model_name='user',
            name='time_zone',
            field=models.ForeignKey(blank=True, help_text='zona horaria', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.timezone', verbose_name='zona horaria'),
        ),
    ]
