# Generated by Django 4.0.4 on 2023-01-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_country_timezone_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.AutoField(editable=False, help_text='id del país', primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='timezone',
            name='id',
            field=models.AutoField(editable=False, help_text='id de la zona horaria', primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
