# Generated by Django 4.0.4 on 2023-01-04 18:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_country_id_alter_timezone_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'País', 'verbose_name_plural': 'Países'},
        ),
        migrations.AlterModelOptions(
            name='timezone',
            options={'verbose_name': 'Zona Horaria', 'verbose_name_plural': 'Zonas Horarias'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(editable=False, help_text='id del stream', primary_key=True, serialize=False, verbose_name='id')),
                ('date', models.DateTimeField(help_text='fecha de inicio del stream', verbose_name='fecha')),
                ('time', models.TimeField(help_text='hora de inicio del stream', verbose_name='hora')),
                ('user', models.ForeignKey(help_text='usuario que está transmitiendo', on_delete=django.db.models.deletion.CASCADE, to='app.user', verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Stream',
                'verbose_name_plural': 'Streams',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(editable=False, help_text='id del comentario', primary_key=True, serialize=False, verbose_name='id')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, help_text='fecha y hora del comentario', verbose_name='fecha y hora')),
                ('comment', models.TextField(help_text='comentario', verbose_name='comentario')),
                ('stream', models.ForeignKey(help_text='stream al que pertenece el comentario', on_delete=django.db.models.deletion.CASCADE, to='app.stream', verbose_name='stream')),
                ('user', models.ForeignKey(help_text='usuario que ha hecho el comentario', on_delete=django.db.models.deletion.CASCADE, to='app.user', verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
            },
        ),
    ]
