# Generated by Django 4.0.4 on 2023-01-04 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_country_options_alter_timezone_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
