# Generated by Django 4.0.4 on 2023-01-04 19:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_comments_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='date',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='time',
        ),
        migrations.AddField(
            model_name='stream',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='fecha y hora del stream', verbose_name='fecha y hora'),
        ),
    ]
