# Generated by Django 4.0.4 on 2023-01-07 01:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_stream_date_remove_stream_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatchCheck',
            fields=[
                ('id', models.AutoField(editable=False, help_text='id del check', primary_key=True, serialize=False, verbose_name='id')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, help_text='fecha y hora del check', verbose_name='fecha y hora')),
                ('stream', models.ForeignKey(help_text='stream al que pertenece el check', on_delete=django.db.models.deletion.CASCADE, to='app.stream', verbose_name='stream')),
                ('user', models.ForeignKey(help_text='usuario que asistió al stream', on_delete=django.db.models.deletion.CASCADE, to='app.user', verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Check',
                'verbose_name_plural': 'Checks',
            },
        ),
    ]
