# Generated by Django 4.0.4 on 2023-01-18 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_whatchcheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(editable=False, help_text='id del estado', primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(help_text='nombre del estado', max_length=100, verbose_name='nombre')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.ForeignKey(default=1, help_text='estado del check', on_delete=django.db.models.deletion.CASCADE, to='app.status', verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='whatchcheck',
            name='status',
            field=models.ForeignKey(default=1, help_text='estado del check', on_delete=django.db.models.deletion.CASCADE, to='app.status', verbose_name='estado'),
        ),
    ]
