# Generated by Django 4.0.4 on 2023-01-18 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_status_comment_status_whatchcheck_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='whatchcheck',
            name='status',
        ),
    ]
