# Generated by Django 4.0.4 on 2023-01-18 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_comment_status_remove_whatchcheck_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.ForeignKey(default=1, help_text='estado del check', on_delete=django.db.models.deletion.CASCADE, to='app.status', verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='whatchcheck',
            name='status',
            field=models.ForeignKey(default=1, help_text='estado del check', on_delete=django.db.models.deletion.CASCADE, to='app.status', verbose_name='estado'),
        ),
    ]
