# Generated by Django 4.0.4 on 2023-01-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_ranking_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ranking',
            field=models.IntegerField(default=0, help_text='ranking del usuario', verbose_name='ranking'),
        ),
    ]
