# Generated by Django 4.0.4 on 2023-01-23 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_ranking_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ranking',
        ),
    ]
