# Generated by Django 4.0.4 on 2023-01-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_user_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_points',
            field=models.IntegerField(default=0, help_text='puntos totales', verbose_name='puntos totales'),
        ),
        migrations.AddField(
            model_name='user',
            name='week_points',
            field=models.IntegerField(default=0, help_text='puntos de la semana', verbose_name='puntos semana'),
        ),
    ]
