# Generated by Django 4.0.4 on 2023-01-24 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_user_total_points_user_week_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='total_points',
        ),
        migrations.RemoveField(
            model_name='user',
            name='week_points',
        ),
        migrations.DeleteModel(
            name='Point',
        ),
    ]
