# Generated by Django 4.0.4 on 2023-01-24 04:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_remove_user_total_points_remove_user_week_points_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralPoint',
            fields=[
                ('id', models.AutoField(editable=False, help_text='id del punto', primary_key=True, serialize=False, verbose_name='id')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, help_text='fecha y hora del punto', verbose_name='fecha y hora')),
                ('stream', models.ForeignKey(help_text='stream al que pertenece el punto', on_delete=django.db.models.deletion.CASCADE, to='app.stream', verbose_name='stream')),
                ('user', models.ForeignKey(help_text='usuario que ha hecho el punto', on_delete=django.db.models.deletion.CASCADE, to='app.user', verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Punto general',
                'verbose_name_plural': 'Puntos generales',
            },
        ),
        migrations.CreateModel(
            name='WeeklyPoint',
            fields=[
                ('id', models.AutoField(editable=False, help_text='id del punto', primary_key=True, serialize=False, verbose_name='id')),
                ('general_point', models.ForeignKey(help_text='punto general al que pertenece el punto', on_delete=django.db.models.deletion.CASCADE, to='app.generalpoint', verbose_name='punto general')),
            ],
            options={
                'verbose_name': 'Punto semanal',
                'verbose_name_plural': 'Puntos semanales',
            },
        ),
        migrations.CreateModel(
            name='DailyPoint',
            fields=[
                ('id', models.AutoField(editable=False, help_text='id del punto', primary_key=True, serialize=False, verbose_name='id')),
                ('general_point', models.ForeignKey(help_text='punto general al que pertenece el punto', on_delete=django.db.models.deletion.CASCADE, to='app.generalpoint', verbose_name='punto general')),
            ],
            options={
                'verbose_name': 'Punto diarios',
                'verbose_name_plural': 'Puntos diarios',
            },
        ),
    ]
