# Generated by Django 4.0.4 on 2023-01-24 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_generalpoint_weeklypoint_dailypoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsHistory',
            fields=[
                ('id', models.AutoField(editable=False, help_text='id del historial', primary_key=True, serialize=False, verbose_name='id')),
                ('general_points', models.IntegerField(help_text='puntos generales', verbose_name='puntos generales')),
                ('week_points', models.IntegerField(help_text='puntos semanales', verbose_name='puntos semanales')),
                ('user', models.ForeignKey(help_text='usuario que ha hecho el punto', on_delete=django.db.models.deletion.CASCADE, to='app.user', verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Punto historial',
                'verbose_name_plural': 'Puntos historial',
            },
        ),
        migrations.CreateModel(
            name='Bits',
            fields=[
                ('id', models.AutoField(editable=False, help_text='id de los bits', primary_key=True, serialize=False, verbose_name='id')),
                ('amount', models.IntegerField(help_text='cantidad de bits', verbose_name='cantidad')),
                ('user', models.ForeignKey(help_text='usuario que ha hecho el punto', on_delete=django.db.models.deletion.CASCADE, to='app.user', verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Bit',
                'verbose_name_plural': 'Bits',
            },
        ),
    ]
