# Generated by Django 4.0.4 on 2023-01-25 03:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_pointshistory_bits'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointshistory',
            options={'verbose_name': 'Historial de puntos generales y semanales', 'verbose_name_plural': 'Historial de puntos'},
        ),
        migrations.CreateModel(
            name='RankingDailyPoint',
            fields=[
                ('id', models.AutoField(editable=False, help_text='id del historial', primary_key=True, serialize=False, verbose_name='id')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, help_text='fecha y hora en que el usuario consiguió los 10 puntos diarios', verbose_name='fecha y hora')),
                ('user', models.ForeignKey(help_text='usuario que ha hecho conseguido 10 puntos diarios', on_delete=django.db.models.deletion.CASCADE, to='app.user', verbose_name='usuario')),
            ],
        ),
    ]
