# Generated by Django 4.0.4 on 2023-01-25 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_pointshistory_options_rankingdailypoint'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RankingDailyPoint',
            new_name='TopDailyPoint',
        ),
    ]
