# Generated by Django 4.0.4 on 2023-01-25 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_rename_rankingdailypoint_topdailypoint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topdailypoint',
            options={'verbose_name': 'Top de usuarios de puntos diarios', 'verbose_name_plural': 'Top de usuarios de puntos diarios'},
        ),
        migrations.AddField(
            model_name='topdailypoint',
            name='position',
            field=models.IntegerField(default=10, help_text='posición del usuario en el top diario', verbose_name='posición'),
        ),
        migrations.AlterField(
            model_name='topdailypoint',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
