# Generated by Django 4.0.4 on 2023-02-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_topdailypoint_options_topdailypoint_position_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topdailypoint',
            options={'verbose_name': 'Top', 'verbose_name_plural': 'Top puntos diarios'},
        ),
        migrations.AddField(
            model_name='ranking',
            name='max_streams',
            field=models.IntegerField(default=0, help_text='máximo de streams que puede tener el usuario para el ranking', verbose_name='máximo de streams'),
        ),
    ]
