# Generated by Django 4.0.4 on 2023-02-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_typepoint_alter_user_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typepoint',
            name='details',
        ),
        migrations.AddField(
            model_name='typepoint',
            name='name',
            field=models.CharField(default='Regular', help_text='nombre del detalle', max_length=100, verbose_name='nombre'),
        ),
    ]
