# Generated by Django 4.0.4 on 2023-02-04 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_remove_typepoint_details_typepoint_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalpoint',
            name='point_type',
            field=models.ForeignKey(default=1, help_text='tipo de punto', on_delete=django.db.models.deletion.CASCADE, to='app.typepoint', verbose_name='tipo de punto'),
        ),
    ]
