# Generated by Django 4.0.4 on 2023-02-04 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_remove_generalpoint_point_type_delete_typepoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalpoint',
            name='amount',
            field=models.IntegerField(default=1, help_text='cantidad de puntos', verbose_name='cantidad'),
        ),
        migrations.AddField(
            model_name='generalpoint',
            name='details',
            field=models.TextField(default='Ver stream', help_text='detalles del punto', verbose_name='detalles'),
        ),
    ]
