# Generated by Django 4.0.4 on 2023-02-04 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_generalpoint_amount_generalpoint_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPoint',
            fields=[
                ('id', models.AutoField(editable=False, help_text='id de la información de punto', primary_key=True, serialize=False, verbose_name='id')),
                ('info', models.TextField(help_text='información del punto', verbose_name='información')),
            ],
        ),
    ]
