# Generated by Django 4.0.4 on 2023-02-04 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_infopoint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infopoint',
            options={'verbose_name': 'Información de punto', 'verbose_name_plural': 'Información de puntos'},
        ),
        migrations.RemoveField(
            model_name='generalpoint',
            name='details',
        ),
        migrations.AlterField(
            model_name='infopoint',
            name='info',
            field=models.CharField(help_text='información del punto', max_length=100, verbose_name='información'),
        ),
    ]
