# Generated by Django 4.0.4 on 2023-02-07 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_alter_user_ranking'),
    ]

    operations = [
        migrations.CreateModel(
            name='StremExtra',
            fields=[
                ('id', models.AutoField(editable=False, help_text='id del stream extra', primary_key=True, serialize=False, verbose_name='id')),
                ('amount', models.IntegerField(default=1, help_text='cantidad de estreams extra', verbose_name='cantidad')),
                ('user', models.ForeignKey(help_text='usuario que ha hecho el punto', on_delete=django.db.models.deletion.CASCADE, to='app.user', verbose_name='usuario')),
            ],
        ),
    ]
