# Generated by Django 4.0.4 on 2023-02-07 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_stremextra'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StremExtra',
            new_name='StreamExtra',
        ),
    ]
