# Generated by Django 4.0.4 on 2023-02-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_rename_stremextra_streamextra'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='is_free',
            field=models.BooleanField(default=False, help_text='indica si el stream es free (no restará puntos)', verbose_name='free'),
        ),
    ]
