# Generated by Django 4.0.4 on 2023-02-07 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_stream_is_free'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='streamextra',
            options={'verbose_name': 'Stream extra', 'verbose_name_plural': 'Streams extra'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.CreateModel(
            name='AdminType',
            fields=[
                ('id', models.AutoField(editable=False, help_text='id del tipo de administrador', primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(help_text='nombre del tipo de administrador', max_length=100, verbose_name='nombre')),
                ('ranking', models.ForeignKey(help_text='ranking asignado al tipo de administrador', on_delete=django.db.models.deletion.CASCADE, to='app.ranking', verbose_name='ranking')),
            ],
            options={
                'verbose_name': 'Tipo de admin',
                'verbose_name_plural': 'Tipos de admins',
            },
        ),
    ]
