# Generated by Django 4.0.4 on 2023-02-07 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_alter_streamextra_options_remove_user_is_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_type',
            field=models.ForeignKey(blank=True, help_text='tipo de administrador del usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.admintype', verbose_name='tipo de administrador'),
        ),
    ]
