# Generated by Django 4.0.4 on 2023-02-08 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_user_admin_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalpoint',
            name='stream',
            field=models.ForeignKey(blank=True, help_text='stream al que pertenece el punto', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.stream', verbose_name='stream'),
        ),
    ]
