# Generated by Django 4.0.4 on 2023-02-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_alter_generalpoint_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='is_vip',
            field=models.BooleanField(default=False, help_text='indica si el stream es vip (único en su hora)', verbose_name='vip'),
        ),
    ]
