# Generated by Django 4.0.4 on 2023-02-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_stream_is_vip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.CharField(blank=True, help_text='foto de perfil de twitch', max_length=200, verbose_name='foto'),
        ),
    ]
