# Generated by Django 4.0.4 on 2023-02-28 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_alter_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamextra',
            name='user',
            field=models.ForeignKey(help_text='usuario al que se le ha asignado el stream extra', on_delete=django.db.models.deletion.CASCADE, to='app.user', verbose_name='usuario'),
        ),
        migrations.CreateModel(
            name='Vips',
            fields=[
                ('id', models.AutoField(editable=False, help_text='id del vip extra', primary_key=True, serialize=False, verbose_name='id')),
                ('amount', models.IntegerField(default=1, help_text='cantidad de vips', verbose_name='cantidad')),
                ('user', models.ForeignKey(help_text='usuario  al que se le ha asignado el vip', on_delete=django.db.models.deletion.CASCADE, to='app.user', verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Vip',
                'verbose_name_plural': 'Vips',
            },
        ),
    ]
