# Generated by Django 4.0.4 on 2023-02-28 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_alter_streamextra_user_vips'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vips',
            new_name='Vip',
        ),
    ]
