# Generated by Django 4.0.4 on 2023-03-02 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0056_alter_infopoint_options_alter_pointshistory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStaff',
            fields=[
                ('id', models.AutoField(editable=False, help_text='id del usuario staff', primary_key=True, serialize=False, verbose_name='id')),
                ('user', models.ForeignKey(help_text='usuario de twitch', on_delete=django.db.models.deletion.CASCADE, to='app.user', verbose_name='usuario')),
                ('user auth', models.ForeignKey(help_text='usuario del dashboard', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario de autenticación')),
            ],
            options={
                'verbose_name': 'Usuario staff relacion',
                'verbose_name_plural': 'Usuarios staff relaciones',
            },
        ),
    ]
