# Generated by Django 4.0.4 on 2023-03-02 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_userstaff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstaff',
            old_name='user auth',
            new_name='user_auth',
        ),
    ]
