# Generated by Django 4.0.4 on 2023-03-02 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0058_rename_user auth_userstaff_user_auth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstaff',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userstaff',
            name='user_auth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='admin_type',
        ),
        migrations.AddField(
            model_name='user',
            name='user_auth',
            field=models.ForeignKey(blank=True, default='', help_text='usuario del dashboard', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario de autenticación'),
        ),
        migrations.DeleteModel(
            name='AdminType',
        ),
        migrations.DeleteModel(
            name='UserStaff',
        ),
    ]
