# Generated by Django 4.0.4 on 2023-03-02 05:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_remove_userstaff_user_remove_userstaff_user_auth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='open_hour',
            field=models.TimeField(default=django.utils.timezone.now, help_text='hora de apertura de agendar stream', verbose_name='hora de apertura de agendar stream'),
        ),
    ]
