# Generated by Django 4.0.4 on 2023-03-09 22:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_ranking_open_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='bits',
            name='details',
            field=models.CharField(blank=True, help_text='detalles de los bits', max_length=100, verbose_name='detalles'),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='open_hour',
            field=models.TimeField(default=django.utils.timezone.now, help_text='hora de apertura de agendar stream', verbose_name='hora de schedule'),
        ),
    ]
