# Generated by Django 4.0.4 on 2023-03-09 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_bits_details_alter_ranking_open_hour'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bits',
            new_name='Bit',
        ),
    ]
