# Generated by Django 4.0.4 on 2023-03-10 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_bit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='claimed_bits',
            field=models.IntegerField(blank=True, default=0, help_text='bits reclamados para este stream', verbose_name='bits reclamados'),
        ),
    ]
