# Generated by Django 4.0.4 on 2023-03-11 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_stream_claimed_bits'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='is_bits_done',
            field=models.BooleanField(default=False, help_text='indica si los bits han sido donados', verbose_name='bits donados'),
        ),
    ]
