# Generated by Django 4.0.4 on 2023-03-12 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_user_is_donnor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_stream_done',
            field=models.BooleanField(default=False, help_text='indica si el usuario ha realizado su primer stream', verbose_name='primer stream'),
        ),
        migrations.AddField(
            model_name='user',
            name='referred_user_from',
            field=models.ForeignKey(blank=True, help_text='usuario que lo referido', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.user', verbose_name='usuario referido de'),
        ),
    ]
