# Generated by Django 4.0.4 on 2023-04-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_remove_bit_date_remove_stream_claimed_bits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='is_free',
            field=models.BooleanField(default=True, help_text='indica si el stream es free (no restará puntos)', verbose_name='free'),
        ),
    ]
