# Generated by Django 4.0.4 on 2023-04-03 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_alter_stream_is_free'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='is_bits_done',
        ),
        migrations.AddField(
            model_name='bit',
            name='is_bits_done',
            field=models.BooleanField(default=False, help_text='indica si los bits han sido donados', verbose_name='bits donados'),
        ),
    ]
