# Generated by Django 4.0.4 on 2023-04-05 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_remove_stream_is_bits_done_bit_is_bits_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailypoint',
            name='general_point',
            field=models.ForeignKey(help_text='punto general al que pertenece el punto', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.generalpoint', verbose_name='punto general'),
        ),
        migrations.AlterField(
            model_name='weeklypoint',
            name='general_point',
            field=models.ForeignKey(help_text='punto general al que pertenece el punto', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.generalpoint', verbose_name='punto general'),
        ),
    ]
