# Generated by Django 4.0.4 on 2023-04-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0072_alter_dailypoint_general_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointshistory',
            name='general_points',
            field=models.IntegerField(help_text='puntos generales hasta el día de hoy', verbose_name='puntos generales totales'),
        ),
        migrations.AlterField(
            model_name='pointshistory',
            name='week_points',
            field=models.IntegerField(help_text='puntos generales obtenidos a lo largo de la semana', verbose_name='puntos generales semana'),
        ),
    ]
