# Generated by Django 4.0.4 on 2023-04-09 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0073_alter_pointshistory_general_points_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointshistory',
            old_name='general_points',
            new_name='general_points_num',
        ),
        migrations.RenameField(
            model_name='pointshistory',
            old_name='week_points',
            new_name='general_points_week_num',
        ),
    ]
