# Generated by Django 4.0.4 on 2023-04-10 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0076_logs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logs',
        ),
    ]
