# Generated by Django 4.0.4 on 2023-04-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0079_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Ajuste', 'verbose_name_plural': 'Ajustes'},
        ),
        migrations.AlterField(
            model_name='settings',
            name='name',
            field=models.CharField(help_text='nombre de la configuración', max_length=100, unique=True, verbose_name='nombre'),
        ),
    ]
