# Generated by Django 4.0.4 on 2023-05-06 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0080_alter_settings_options_alter_settings_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='fecha y hora del comentario', null=True, verbose_name='fecha y hora'),
        ),
    ]
