# Generated by Django 4.0.4 on 2023-05-06 13:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0081_alter_comment_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='fecha y hora del comentario', verbose_name='fecha y hora'),
        ),
    ]
