# Generated by Django 4.0.4 on 2023-06-15 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0084_weeklypointbackup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WhatchCheck',
        ),
    ]
