# Generated by Django 4.0.4 on 2023-07-06 04:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0086_generalpoint_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(choices=[('set_ranking_delete_points', 'Set Ranking Delete Points'), ('node_comments', 'Node Comments'), ('read_chat', 'Read Chat'), ('calculate_points', 'Calculate Points'), ('update_tokens', 'Update Tokens')], help_text='origen del log', max_length=100, verbose_name='origen')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, help_text='fecha y hora del log', verbose_name='fecha y hora')),
                ('details', models.CharField(blank=True, help_text='detalles del log', max_length=100, verbose_name='detalles')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
            },
        ),
    ]
