# Generated by Django 4.0.4 on 2023-07-06 05:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0086_generalpoint_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.IntegerField(default=1, help_text='origen del log', verbose_name='origen')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, help_text='fecha y hora del log', verbose_name='fecha y hora')),
                ('details', models.CharField(blank=True, help_text='detalles del log', max_length=100, verbose_name='detalles')),
                ('log_type', models.IntegerField(default=1, help_text='tipo de log', verbose_name='tipo')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
            },
        ),
        migrations.CreateModel(
            name='LogOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='nombre del origen del log', max_length=100, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'Origen de log',
                'verbose_name_plural': 'Orígenes de logs',
            },
        ),
        migrations.CreateModel(
            name='LogType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='nombre del tipo de log', max_length=100, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'Tipo de log',
                'verbose_name_plural': 'Tipos de logs',
            },
        ),
    ]
