# Generated by Django 4.0.4 on 2023-07-06 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0087_log_logorigin_logtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='log_type',
            field=models.ForeignKey(default=1, help_text='tipo de log', on_delete=django.db.models.deletion.CASCADE, to='app.logtype', verbose_name='tipo de log'),
        ),
        migrations.AlterField(
            model_name='log',
            name='origin',
            field=models.ForeignKey(help_text='origen del log', on_delete=django.db.models.deletion.CASCADE, to='app.logorigin', verbose_name='origen'),
        ),
    ]
