# Generated by Django 4.0.4 on 2023-07-06 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0088_alter_log_log_type_alter_log_origin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={},
        ),
        migrations.AlterModelOptions(
            name='logorigin',
            options={},
        ),
        migrations.AlterModelOptions(
            name='logtype',
            options={},
        ),
    ]
