# Generated by Django 4.0.4 on 2023-07-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0093_alter_generalpoint_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='send_mail',
            field=models.BooleanField(default=True, help_text='indica si el usuario quiere recibir emails', verbose_name='enviar email'),
        ),
    ]
