# Generated by Django 4.0.4 on 2023-07-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0094_user_send_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topdailypoint',
            name='position',
        ),
        migrations.AddField(
            model_name='topdailypoint',
            name='amount',
            field=models.IntegerField(default=10, help_text='cantidad de puntos diarios', verbose_name='cantidad'),
        ),
    ]
