# Generated by Django 4.0.4 on 2023-08-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0095_remove_topdailypoint_position_topdailypoint_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topdailypoint',
            name='datetime',
            field=models.DateTimeField(auto_now=True, help_text='fecha y hora en que el usuario consiguió los 10 puntos diarios', verbose_name='fecha y hora'),
        ),
    ]
