# Generated by Django 4.0.4 on 2023-08-10 16:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0097_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_update_token',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='fecha de última actualización de token', verbose_name='última actualización de token'),
        ),
        migrations.AddField(
            model_name='user',
            name='update_tries',
            field=models.IntegerField(default=0, help_text='cantidad de intentos de actualización de token', verbose_name='intentos de actualización'),
        ),
    ]
