# Generated by Django 4.2.7 on 2023-12-28 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0098_user_last_update_token_user_update_tries'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleStreams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(help_text='fecha y hora de inicio de stream agendados', verbose_name='fecha y hora de inicio')),
                ('end_date', models.DateTimeField(help_text='fecha y hora de fin de streams agendados', verbose_name='fecha y hora de fin')),
                ('monday', models.BooleanField(default=True, help_text='indica si el stream está agendado para los lunes', verbose_name='lunes')),
                ('tuesday', models.BooleanField(default=True, help_text='indica si el stream está agendado para los martes', verbose_name='martes')),
                ('wednesday', models.BooleanField(default=True, help_text='indica si el stream está agendado para los miércoles', verbose_name='miércoles')),
                ('thursday', models.BooleanField(default=True, help_text='indica si el stream está agendado para los jueves', verbose_name='jueves')),
                ('friday', models.BooleanField(default=True, help_text='indica si el stream está agendado para los viernes', verbose_name='viernes')),
                ('saturday', models.BooleanField(default=True, help_text='indica si el stream está agendado para los sábados', verbose_name='sábado')),
                ('time', models.TimeField(help_text='hora de inicio de stream agendados', verbose_name='hora')),
                ('user', models.ForeignKey(help_text='usuario que ha agendado el stream', on_delete=django.db.models.deletion.CASCADE, to='app.user', verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Stream programado',
                'verbose_name_plural': 'Streams programados',
            },
        ),
    ]
