# Generated by Django 4.2.7 on 2023-12-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0100_alter_schedulestreams_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulestreams',
            name='end_date',
            field=models.DateField(help_text='fecha y hora de fin de streams agendados', verbose_name='fecha y hora de fin'),
        ),
        migrations.AlterField(
            model_name='schedulestreams',
            name='start_date',
            field=models.DateField(help_text='fecha y hora de inicio de stream agendados', verbose_name='fecha y hora de inicio'),
        ),
    ]
