# Generated by Django 4.2.7 on 2023-12-28 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0102_alter_schedulestreams_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulestreams',
            name='end_date',
            field=models.DateField(help_text='fecha y hora de fin de streams agendados', verbose_name='fecha y hora de fin'),
        ),
        migrations.AlterField(
            model_name='schedulestreams',
            name='friday',
            field=models.BooleanField(default=True, help_text='indica si el stream está agendado para los viernes', verbose_name='viernes'),
        ),
        migrations.AlterField(
            model_name='schedulestreams',
            name='monday',
            field=models.BooleanField(default=True, help_text='indica si el stream está agendado para los lunes', verbose_name='lunes'),
        ),
        migrations.AlterField(
            model_name='schedulestreams',
            name='saturday',
            field=models.BooleanField(default=True, help_text='indica si el stream está agendado para los sábados', verbose_name='sábado'),
        ),
        migrations.AlterField(
            model_name='schedulestreams',
            name='start_date',
            field=models.DateField(help_text='fecha y hora de inicio de stream agendados', verbose_name='fecha y hora de inicio'),
        ),
        migrations.AlterField(
            model_name='schedulestreams',
            name='thursday',
            field=models.BooleanField(default=True, help_text='indica si el stream está agendado para los jueves', verbose_name='jueves'),
        ),
        migrations.AlterField(
            model_name='schedulestreams',
            name='time',
            field=models.TimeField(help_text='hora de inicio de stream agendados', verbose_name='hora'),
        ),
        migrations.AlterField(
            model_name='schedulestreams',
            name='user',
            field=models.ForeignKey(help_text='usuario que ha agendado el stream', on_delete=django.db.models.deletion.CASCADE, to='app.user', verbose_name='usuario'),
        ),
        migrations.AlterField(
            model_name='schedulestreams',
            name='wednesday',
            field=models.BooleanField(default=True, help_text='indica si el stream está agendado para los miércoles', verbose_name='miércoles'),
        ),
    ]
