# Generated by Django 4.0.4 on 2023-05-14 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botcheers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Usuario que ha realizado la donación', null=True, on_delete=django.db.models.deletion.CASCADE, to='botcheers.user', verbose_name='Usuario'),
        ),
    ]
