# Generated by Django 4.0.4 on 2023-05-14 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('botcheers', '0002_donation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_auth',
            field=models.ForeignKey(blank=True, help_text='Usuario de autenticación', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_auth_cheers', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de autenticación'),
        ),
    ]
