# Generated by Django 4.0.4 on 2023-05-22 06:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('botcheers', '0003_donation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='minute',
        ),
        migrations.AddField(
            model_name='donation',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 5, 22, 6, 19, 42, 221531, tzinfo=utc), help_text='Hora de la donación', verbose_name='Hora'),
        ),
    ]
