# Generated by Django 4.0.4 on 2023-05-14 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botcheers', '0003_user_user_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='hour',
            field=models.IntegerField(help_text='Hora de la donación (de 0 a 23)', verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='minute',
            field=models.IntegerField(help_text='Minuto de la donación (de 0 a 59)', verbose_name='Minuto'),
        ),
    ]
