# Generated by Django 4.0.4 on 2023-05-15 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botcheers', '0004_alter_donation_hour_alter_donation_minute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='hour',
            field=models.IntegerField(help_text='Hora de la donación (de 0 a 23)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)], verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='minute',
            field=models.IntegerField(help_text='Minuto de la donación (de 0 a 59)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)], verbose_name='Minuto'),
        ),
    ]
