# Generated by Django 4.0.4 on 2023-05-24 06:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('botcheers', '0008_alter_donation_stream_chat_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='time',
        ),
        migrations.AddField(
            model_name='donation',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de la donación', verbose_name='Fecha y hora'),
        ),
    ]
