# Generated by Django 4.0.4 on 2023-05-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botcheers', '0009_remove_donation_time_donation_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(help_text='Host del proxy', max_length=50, verbose_name='Host')),
                ('port', models.IntegerField(help_text='Puerto del proxy', verbose_name='Puerto')),
                ('user', models.CharField(help_text='Usuario del proxy', max_length=50, verbose_name='Usuario')),
                ('password', models.CharField(help_text='Contraseña del proxy', max_length=50, verbose_name='Contraseña')),
            ],
            options={
                'verbose_name': 'Proxy',
                'verbose_name_plural': 'Proxies',
            },
        ),
    ]
