# Generated by Django 4.0.4 on 2023-05-26 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botcheers', '0010_proxy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proxy',
            name='password',
        ),
        migrations.RemoveField(
            model_name='proxy',
            name='user',
        ),
    ]
