# Generated by Django 4.0.4 on 2023-06-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botcheers', '0011_remove_proxy_password_remove_proxy_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', help_text='Contraseña del usuario', max_length=50, verbose_name='Contraseña'),
        ),
    ]
