# Generated by Django 4.0.4 on 2023-06-19 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botcheers', '0012_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad')),
            ],
        ),
        migrations.CreateModel(
            name='BitsSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0, verbose_name='Balance')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='ComunidadMC', help_text='Contraseña del usuario', max_length=50, verbose_name='Contraseña'),
        ),
    ]
