# Generated by Django 4.0.4 on 2023-06-19 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botcheers', '0013_bitshistory_bitssummary_alter_user_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bitshistory',
            options={'verbose_name': 'Historial de bits', 'verbose_name_plural': 'Historiales de bits'},
        ),
        migrations.AlterModelOptions(
            name='bitssummary',
            options={'verbose_name': 'Resumen de bits', 'verbose_name_plural': 'Resúmenes de bits'},
        ),
    ]
