# Generated by Django 4.0.4 on 2023-06-19 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botcheers', '0014_alter_bitshistory_options_alter_bitssummary_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitssummary',
            name='balance',
        ),
    ]
