# Generated by Django 4.0.4 on 2023-06-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botcheers', '0015_remove_bitssummary_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitssummary',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='Balance'),
        ),
    ]
