# Generated by Django 4.0.4 on 2023-06-19 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botcheers', '0016_bitssummary_balance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BitsHistory',
        ),
        migrations.DeleteModel(
            name='BitsSummary',
        ),
    ]
