# Generated by Django 4.0.4 on 2023-06-19 23:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('botcheers', '0017_delete_bitshistory_delete_bitssummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitsSummary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Fecha y hora de ultima actualización')),
                ('balance', models.IntegerField(default=0, verbose_name='Balance')),
                ('bot', models.ForeignKey(help_text='Bot de bits', on_delete=django.db.models.deletion.CASCADE, to='botcheers.user')),
            ],
            options={
                'verbose_name': 'Resumen de bits',
                'verbose_name_plural': 'Resúmenes de bits',
            },
        ),
        migrations.CreateModel(
            name='BitsHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora')),
                ('amount', models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad')),
                ('donation', models.ForeignKey(blank=True, help_text='Donación asociada al historial', null=True, on_delete=django.db.models.deletion.CASCADE, to='botcheers.donation')),
            ],
            options={
                'verbose_name': 'Historial de bits',
                'verbose_name_plural': 'Historiales de bits',
            },
        ),
    ]
