# Generated by Django 4.0.4 on 2023-06-19 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botcheers', '0018_bitssummary_bitshistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bitssummary',
            old_name='bot',
            new_name='user',
        ),
    ]
