# Generated by Django 4.0.4 on 2023-06-19 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botcheers', '0019_rename_bot_bitssummary_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bitshistory',
            options={'verbose_name': 'Bits historial', 'verbose_name_plural': 'Bits historiales'},
        ),
        migrations.AlterModelOptions(
            name='bitssummary',
            options={'verbose_name': 'Bits resumen', 'verbose_name_plural': 'Bits resumenes'},
        ),
    ]
