# Generated by Django 4.0.4 on 2023-06-19 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botcheers', '0020_alter_bitshistory_options_alter_bitssummary_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitshistory',
            name='donation',
        ),
        migrations.AddField(
            model_name='bitshistory',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='botcheers.user', verbose_name='Bot de bits'),
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=0, help_text='Balance de bits del usuario', verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='bitshistory',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Cantidad'),
        ),
        migrations.DeleteModel(
            name='BitsSummary',
        ),
    ]
