# Generated by Django 4.0.4 on 2023-06-21 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botcheers', '0021_remove_bitshistory_donation_bitshistory_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitshistory',
            name='donation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='botcheers.donation', verbose_name='Donación'),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=0, editable=False, help_text='Balance de bits del usuario', verbose_name='Balance'),
        ),
    ]
