# Generated by Django 4.0.4 on 2023-06-23 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botcheers', '0022_bitshistory_donation_alter_user_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=0, help_text='Balance de bits del usuario', verbose_name='Balance'),
        ),
    ]
