# Generated by Django 4.0.4 on 2023-06-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botcheers', '0023_alter_user_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cookies',
            field=models.JSONField(default={'sample': 'sample'}, editable=False, help_text='Cookies de sesión del usuario', verbose_name='Cookies'),
        ),
    ]
