# Generated by Django 4.0.4 on 2023-08-03 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botcheers', '0028_remove_donation_bits_app_donation_stream_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='user',
            field=models.ForeignKey(help_text='Usuario que ha realizado la donación', on_delete=django.db.models.deletion.CASCADE, to='botcheers.user', verbose_name='Usuario'),
        ),
    ]
