# Generated by Django 4.0.4 on 2023-08-03 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0095_remove_topdailypoint_position_topdailypoint_amount'),
        ('botcheers', '0029_alter_donation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='stream_app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.stream', verbose_name='Stream de bits reclamados'),
        ),
    ]
