# Generated by Django 4.0.4 on 2023-08-17 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0098_user_last_update_token_user_update_tries'),
        ('botcheers', '0031_remove_donation_stream_app_donation_bits_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='bits_app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.bit', verbose_name='Bits reclamados'),
        ),
    ]
